### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by johannesnydahl** [jessephamel/VidGrid#2]
Somehow, when i try run vidgrid.py, i get this error

Traceback (most recent call last):
  File "vidgrid.py", line 1, in <module>
    from moviepy.editor import *
  File "C:\Users\04nyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy-0.2.3.2-py3.6.egg\moviepy\editor.py", line 24, in <module>
    from .video.io.downloader import download_webfile
  File "C:\Users\04nyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy-0.2.3.2-py3.6.egg\moviepy\video\io\downloader.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by johannesnydahl** [comment]
okay i fixed it, but now i get these:

usage: vidgrid.py [-h] [-o O] [-rows ROWS] [-d D] [-rand RAND] input
vidgrid.py: error: the following arguments are required: input

**Comment by ayunami2000** [comment]
u need the input video specified
